[tool.poetry]
name = "ai-storytelling"
version = "0.1.0"
description = "AI and Storytelling Central Codebase"
authors = ["Patrick Kage <p.kage@ed.ac.uk>"]

[tool.poetry.dependencies]
python = "^3.9"
transformers = {extras = ["torch"], version = "^4.20.1"}
ipykernel = "^6.15.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
